- name: Enable or Disable Instance's on AAP
  hosts: localhost
  tasks:
    - name: Interaction
      ansible.controller.instance:
        hostname: "{{ CONTROLLER_HOSTNAME }}"
        enabled: "{{ CONTROLLER_STATE }}"
        controller_host: "{{ CONTROLLER_HOST }}"